Adding a horrible hack to fake availableReplicas
openfaas-incubator/faas-rancher pull request #5
Opened 2019-01-05 01:56 UTC by jgnagy

I'm no Go developer so feel free to make fun of anything I did wrong here. I was able to run `make build` and it seems to have succeeded but I wasn't sure how to run unit tests.

@alexellis and @kenfdev please let me know if I need to do this differently.

2019-01-05 08:48 UTC, alexellis commented
You have 4 commits now, so do: `git reset HEAD~4`  then git add and commit -s followed by a force push. That should sort things out.

Alex

2019-01-12 14:22 UTC, kenfdev requested changes
Thank you @jgnagy for your contribution. This change seems reasonable since currently faas-rancher and the new gateway can't use the gateway UI.

Few things I want to make sure:

* How did you update the vendor file? This repo uses [rancher/trash](https://github.com/rancher/trash) for vendors. (not `dep` IIRC).
* Could you provided a little more information about how you tested this?

2019-01-12 14:22 UTC, kenfdev commented on handlers/replicas.go
> +		found.AvailableReplicas = found.Replicas
Seems reasonable. But could you leave a comment about faking the information? Thanks ;)

2019-01-12 15:15 UTC, alexellis commented
Let's switch to dep Ken?

2019-01-12 15:18 UTC, kenfdev commented
> Let's switch to dep Ken?

I'm not against that and that's a reasonable change, too. 
Unfortunately, I don't have the time to do it myself but if @jgnagy or someone in the community could take it, I'm more than happy to review it.

2019-01-25 22:25 UTC, jgnagy commented
#7 is a **much** better approach. This PR is no longer necessary.

2019-01-25 22:25 UTC, closed without merging